# Vector configuration for Sentry sink demo
# Send logs from stdin to Sentry

sources:
  demo_logs:
    type: "demo_logs"
    format: "syslog"

sinks:
  sentry_sink:
    inputs: ["demo_logs"]
    type: "sentry"
    dsn: "https://4865bee93ec668370e59ed2862ed05a0@o447951.ingest.us.sentry.io/4509675223187456"
    encoding:
      codec: "text"
