relay:
  mode: static
  upstream: https://sentry.io
  host: 0.0.0.0
  port: 3000

logging:
  level: debug
  format: json
  enable_backtraces: true

limits:
  max_concurrent_requests: 50
  max_event_size: 1MiB

cache:
  project_expiry: 300
  envelope_expiry: 600
